# Generated by Django 4.2.26 on 2026-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_rentability_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_to_usd', models.DecimalField(decimal_places=6, default=0.021661, max_digits=12, verbose_name='1 TL in USD')),
                ('try_to_eur', models.DecimalField(decimal_places=6, default=0.018768, max_digits=12, verbose_name='1 TL in EUR')),
                ('try_to_dzd', models.DecimalField(decimal_places=6, default=5, help_text='Default business rate: 100 TL = 500 DZD.', max_digits=12, verbose_name='1 TL in DZD')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency settings',
                'verbose_name_plural': 'Currency settings',
            },
        ),
    ]
