# Generated by Django 4.2.26 on 2026-06-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_whatsappconversation_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppIdentityAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, db_index=True, max_length=80)),
                ('alias', models.CharField(db_index=True, max_length=160)),
                ('canonical_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_aliases', to='listings.whatsappconversation')),
            ],
            options={
                'ordering': ('alias',),
                'unique_together': {('session', 'alias')},
            },
        ),
    ]
