# Generated by Django 4.2.26 on 2026-06-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_whatsappidentityalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
