# Generated by Django 4.2.26 on 2026-06-12 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPhoneEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=32)),
                ('phone_raw', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('missing', 'Missing'), ('error', 'Error'), ('skipped', 'Skipped')], db_index=True, default='missing', max_length=16)),
                ('source', models.CharField(db_index=True, default='android_visible_index', max_length=80)),
                ('source_result_path', models.CharField(blank=True, max_length=500)),
                ('debug_folder', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_entries', to='listings.listing')),
            ],
            options={
                'ordering': ('-scraped_at', '-updated_at'),
                'unique_together': {('external_id', 'source')},
            },
        ),
    ]
