# Generated by Django 4.2.26 on 2026-06-12 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_listingphoneentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingphoneentry',
            name='scraped_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
