"""
Django settings for coralcity project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_env_file(path):
    if not os.path.exists(path):
        return
    with open(path, encoding='utf-8') as env_file:
        for raw_line in env_file:
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


load_env_file(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+=mb2q!t+yg7(m$!_$iki#2*z(+ub^lcas0jx$l2-dp%bp8pt)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    # Include existing trusted origins
    "https://*.lotfinity.tech", # Use a wildcard for subdomains if applicable
    "https://kuzey-emlak.lotfinity.tech", # Explicitly add the specific origin
    # You might also need to include your local development server, e.g.,
    # "http://127.0.0.1:8000",
]
# Application definition

INSTALLED_APPS = [
    # Baton (if installed) must precede 'django.contrib.admin' to style the admin
    # We'll insert it dynamically below if available
    'baton',
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'pages.apps.PagesConfig',
    'Ages.apps.AgesConfig',
    'listings.apps.ListingsConfig',
    'realtors.apps.RealtorsConfig',
    'accounts.apps.AccountsConfig',
    'contacts.apps.ContactsConfig',
    'django.contrib.humanize',
    'blog',
    'import_export',
    'graphene_django',
    'django_distill',
    'easy_thumbnails',
    'baton.autodiscover',

]

# Add Rosetta only if available to avoid startup failures when not installed
try:
    import baton  # noqa: F401
    # Insert 'baton' before 'django.contrib.admin' to override admin templates
    if 'baton' not in INSTALLED_APPS:
        admin_index = INSTALLED_APPS.index('django.contrib.admin') if 'django.contrib.admin' in INSTALLED_APPS else 0
        INSTALLED_APPS.insert(admin_index, 'baton')
    # Autodiscover app configs to allow Baton to tweak admin apps
    if 'baton.autodiscover' not in INSTALLED_APPS:
        INSTALLED_APPS.append('baton.autodiscover')
except Exception:
    pass

# Add Rosetta only if available to avoid startup failures when not installed
try:
    import rosetta  # noqa: F401
    INSTALLED_APPS.append('rosetta')
except Exception:
    pass

# Optionally enable image_uploader_widget for nicer admin image uploads
try:
    import image_uploader_widget  # noqa: F401
    INSTALLED_APPS.append('image_uploader_widget')
except Exception:
    pass

# During static builds, drop debug_toolbar entirely so assets aren't collected
if any(cmd in sys.argv for cmd in ('distill-local', 'distill-publish')):
    # Remove debug_toolbar and optional/incompatible apps for static builds
    INSTALLED_APPS = [
        app for app in INSTALLED_APPS
        if app not in ('debug_toolbar', 'graphene_django')
    ]
    # When building static output, it's usually preferable to emit collected
    # assets into the distill folder so a single directory is deployable.
    # You can still override via COLLECT_STATIC_TO_DISTILL=0.
    if os.environ.get('COLLECT_STATIC_TO_DISTILL', '1') == '1':
        try:
            DISTILL_DIR  # ensure defined above
            STATIC_ROOT = os.path.join(DISTILL_DIR, 'static')
        except Exception:
            pass

GRAPHENE = {
    'SCHEMA': 'blog.schema.schema'
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF =  'coralcity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR , 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pages.context_processors.theme_settings',
                'listings.context_processors.currency_settings',
            ],
        },
    },
]

WSGI_APPLICATION =  'coralcity.wsgi.application'
ASGI_APPLICATION = 'coralcity.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

REDIS_URL = os.environ.get('REDIS_URL') or os.environ.get('CHANNEL_REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'listings.whatsapp': {
            'handlers': ['console'],
            'level': os.environ.get('WHATSAPP_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

import os
DISTILL_DIR = os.path.join(BASE_DIR, 'distill_output')

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

WAHA_URL = os.environ.get('WAHA_URL', '').rstrip('/')
WAHA_API_KEY = os.environ.get('WAHA_API_KEY', '')
AIRBNB_SCRAPER_API_KEY = os.environ.get('AIRBNB_SCRAPER_API_KEY', '')
WAHA_SESSION_DEFAULT = os.environ.get('WAHA_SESSION_DEFAULT', os.environ.get('WAHA_DEFAULT_SESSION', 'default'))
WAHA_DEFAULT_COUNTRY_CODE = os.environ.get('WAHA_DEFAULT_COUNTRY_CODE', '90')

WHATSAPP_AI_ENABLED = os.environ.get('WHATSAPP_AI_ENABLED', '1').lower() not in ('0', 'false', 'no', 'off')
WHATSAPP_AI_MODEL = os.environ.get('WHATSAPP_AI_MODEL', 'moonshotai/kimi-k2.6')
WHATSAPP_AI_API_KEY = (
    os.environ.get('WHATSAPP_AI_API_KEY')
    or os.environ.get('NVIDIA_NIM_API_KEY')
    or os.environ.get('NVIDIA_API_KEY')
    or os.environ.get('LITELLM_API_KEY')
    or ''
)
WHATSAPP_AI_API_BASE = os.environ.get('WHATSAPP_AI_API_BASE', os.environ.get('NVIDIA_NIM_API_BASE', 'https://aigw.whatsynaptic.com')).rstrip('/')
WHATSAPP_AI_MAX_TOKENS = int(os.environ.get('WHATSAPP_AI_MAX_TOKENS', '180'))
WHATSAPP_AI_TEMPERATURE = float(os.environ.get('WHATSAPP_AI_TEMPERATURE', '0.35'))



# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Istanbul' 

USE_I18N = True

USE_L10N = True

USE_TZ = True

# i18n/l10n configuration
LANGUAGES = [
    ('en', 'English'),
    ('tr', 'Türkçe'),
    ('fr', 'Français'),
    ('es', 'Español'),
    ('it', 'Italiano'),
    ('pl', 'Polski'),
    ('pt', 'Português'),
    ('hu', 'Magyar'),
    ('ru', 'Русский'),
    ('ar', 'العربية'),
    ('de', 'Deutsch'),        # German
    ('bg', 'български'),      # Bulgarian
    ('nl', 'Nederlands'),     # Dutch
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Rosetta: auto-compile .po files into .mo on save (requires gettext on system)
ROSETTA_AUTO_COMPILE = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# STATIC_ROOT is where collectstatic gathers all static files (for production/Docker)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# STATICFILES_DIRS are additional directories where Django looks for static files
# This includes your project-level static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'coralcity/static'),
]


# Media Folder Settings
# Default media root (original uploads). For static exports, copy this to
# os.path.join(DISTILL_DIR, 'media') using a helper command.
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Optional convenience path for static builds
DISTILL_MEDIA_ROOT = os.path.join(DISTILL_DIR, 'media')
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# settings.py

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',

}

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if 'DATABASE_URL' in os.environ:
    import dj_database_url
    DATABASES = {'default': dj_database_url.config()}

# Optional Baton configuration (safe if baton not installed)
BATON = {
    'SITE_HEADER': 'Kuzey Emlak Yönetim',
    'SITE_TITLE': 'Kuzey Emlak Yönetim',
    'INDEX_TITLE': 'Site administration',
    'SUPPORT_HREF': '#',
    'CONFIRM_UNSAVED_CHANGES': True,
    'ENABLE_IMAGES_PREVIEW': True,
}

# easy-thumbnails configuration
THUMBNAIL_ALIASES = {
    '': {
        'thumb': {'size': (300, 200), 'crop': True},
        'card': {'size': (600, 400), 'crop': True},
        'detail': {'size': (1200, 800), 'crop': True},
        'admin': {'size': (160, 100), 'crop': True},
    },
}
THUMBNAIL_BASEDIR = 'thumbnails'
THUMBNAIL_DEFAULT_OPTIONS = {
    'quality': 85,
}
